name: Cross-platform Release

on:
  push:
    tags:
      - "[0-9]*"

permissions:
  contents: write
  packages: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set version variable
        run: echo "VERSION=$(bash ./scripts.dev/get-version.sh)" >> $GITHUB_ENV

      # - name: Verify tag and Cargo version match
      #   run: |
      #     TAG=${GITHUB_REF_NAME#v}
      #     [ "$VERSION" = "$TAG" ]

      - name: Cache
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run tests
        run: |
          cd rust
          cargo test --all-targets

      - name: Build release
        run: |
          cd rust
          cargo build --release --all-targets

      - name: Package binaries (Unix-like)
        if: runner.os != 'Windows'
        run: |
          mkdir -p release
          cp rust/target/release/{limabean,limabean-pod} release/
          tar czvf limabean-${{ matrix.os }}.tar.gz -C release .

      - name: Package binaries (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          mkdir -p release
          $bins = @(
            "rust\target\release\limabean.exe",
            "rust\target\release\limabean-pod.exe"
          )
          Copy-Item $bins release\
          Compress-Archive -Path release\* -DestinationPath limabean-${{ matrix.os }}.zip

      - name: Upload Rust binaries
        uses: actions/upload-artifact@v6
        with:
          name: limabean-${{ matrix.os }}
          path: |
            limabean-${{ matrix.os }}.tar.gz
            limabean-${{ matrix.os }}.zip

      - name: Setup Clojure
        if: matrix.os == 'ubuntu-latest'
        uses: DeLaGuardo/setup-clojure@13
        with:
          cli: latest

      - name: Build uberjar
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd clj
          clojure -T:build uber
          mv target/limabean-${GITHUB_REF_NAME#v}-standalone.jar ../limabean-standalone.jar

      - name: Upload uberjar
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v6
        with:
          name: limabean-uberjar
          path: |
            limabean-standalone.jar

      - name: Build container image
        if: matrix.os == 'ubuntu-latest'
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          base-image: docker.io/clojure:tools-deps
          image: ${{ github.event.repository.name }}
          tags: ${{ env.VERSION }} latest
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
          content: |
            limabean-standalone.jar
            release/limabean
            release/limabean-pod
          entrypoint: limabean
          envs: |
            LIMABEAN_UBERJAR=/limabean-standalone.jar
          workdir: /data
          extra-args: -v .:/data

      - name: Echo Outputs
        run: |
          echo "### Build :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "Image: ${{ steps.build-image.outputs.image }}" >> $GITHUB_STEP_SUMMARY
          echo "Tags: ${{ steps.build-image.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
          echo "Tagged Image: ${{ steps.build-image.outputs.image-with-tag }}" >> $GITHUB_STEP_SUMMARY

      - name: Push to the Github Container Registry
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
